# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
create_claude_symlink: false
create_gemini_symlink: false
data_format: string
file_extension: ''
has_ai_rules: true
has_binder: false
kind: mimerenderer
labextension_name: jupyter-ai-chat-components
mimetype: application/vnd.jupyter.chat.components
mimetype_name: ''
project_short_description: Components to displayed in jupyter chat
python_name: jupyter_ai_chat_components
repository: https://github.com/brichet/jupyter-ai-chat-components
test: true
viewer_name: ''

